### ISSUE TITLE
Textures look regressions in latest gl4es

### ISSUE THREAD

**Issue by kas1e** [ptitSeb/gl4es#105]
Found that at least since few revisions, we have some issues on how some textures looks like. They start to be "blocky" and "pixeled" much. There is some screenshots, sorry they not on my host (have problems now), but hope you can see it from free-hosting as well. 

There is for example how start to looks like RTCW Reboorn now:

https://ibb.co/q9Y98hP

There is how start to looks like loading screen in the Quake3:

https://ibb.co/dGhGNw5

And for reference how should looks like (and how it looks like with some previous gl4es versions) that quake3 loading screen:

https://ibb.co/ngpfdrF

Its like some effect gone, or some aliasing. 

And that happens in all the places of some games,  letters start to be a bit blocky, some words , etc.

**Comment by ptitSeb** [comment]
I think this is a filter issue. It looks like it's applying GL_NEAREST instead of GL_LINEAR (or maybe some MIPMAP variant).
I'll check tonight on the Pandora to see if I lso have this issue on my side.

Can you try to `git bisect` to pinpoint the commit that break that?

**Comment by kas1e** [comment]
> Can you try to git bisect to pinpoint the commit that break that?

Sadly i didn't use GIT with GL4ES, i just manually download .ziped versions from the web of latest sources, and build them in some another directory so to have many directories of gl4es with different commits. 

But i can say at least in which ones of latest it works for sure, need 10 minutes

**Comment by ptitSeb** [comment]
Ah ok, no git.

Anyway, I assume the only commit that can have this effect is 8ad7cb18fd0401da55524ee22e9f7aa794def0a2
Are you using LIBGL_BATCH also?

**Comment by kas1e** [comment]
> Anyway, I assume the only commit that can have this effect is 8ad7cb1
Yeah, this one is broke things. Previous one works

> Are you using LIBGL_BATCH also?
Nope, all default.

**Comment by ptitSeb** [comment]
I'm sorry, but I don't reproduce the issue on my side.

I have done a GLES capture, to be sure, and it's all good. I see the texture, the correct filter (GL_LINEAR in that case) is applied, on the small 128x128 GL_RGB texture (that have no mipmap).

So that's really strange.

To try understand what is happening, using latest gl4es sources, can you try, in `src/gl/texture.c` line 1956 to change `if(!glstate->list.pending) {`with `if(1) {` ?

**Comment by kas1e** [comment]
Will check now.

You tried ogles2 no ogles1 , right ?

**Comment by ptitSeb** [comment]
Yep, I tried only the GLES2 backend.

**Comment by kas1e** [comment]
With `if(1) {` no changes, same pixelized texture.

To add, RTCW Reboorn compiled not by me, but by Huno (so , he have his own SDL, his own stuff, etc,etc), and issue come once he build new version with latest gl4es.

Strange ! Maybe endianes somewhere/somehow ? Dunno..

**Comment by ptitSeb** [comment]
Then I guess the issue is with the new iff in line 1993:
try changing `if (pname==GL_TEXTURE_MIN_FILTER) { if(texture->min_filter == param) return; texture->min_filter = param; }` to `if (pname==GL_TEXTURE_MIN_FILTER) { /*if(texture->min_filter == param) return; */texture->min_filter = param; }` and the same type of change line 1994.

**Comment by ptitSeb** [comment]
And my guess is the change in line 1994 fix the thing. And if that's the case, that means the issue is with the default value of MAG filter for texture, that should be GL_LINEAR and not GL_NEAREST (look at the spec here: https://www.khronos.org/registry/OpenGL-Refpages/es2.0/xhtml/glTexParameter.xml for the default for other parameters).
With that commit, I don't change Texture parameter if unneeded, and gl4es expect Mag filter to be GL_LINEAR...

**Comment by kas1e** [comment]
With changes in line 1993 and 1994 , bug gone.

Tried also just 1994, without touching 1993 : bug also gone

So that mean another bugreport for ogles2.library then :)

**Comment by ptitSeb** [comment]
yep, looks like that.

If needed, I can add some `#ifdef` to gl4es, but it would be better to adjust gles2 driver I think.

**Comment by kas1e** [comment]
Yeah, no needs for ifdefs, better to fix gles2 for sure.

Thanks for time :)

ps. did you have by any luck some time to try if frickingshark works with shaders on your setup ?

**Comment by ptitSeb** [comment]
Not yet. I'll see if I can launch it tonight...

**Comment by ptitSeb** [comment]
Friking Shark is fine on my side...

Here end of log:
```
COpenGLModel::LoadFromFile -> Loaded model ./Models/SmallShip.ase (52 ms)
COpenGLTexture::LoadFromFile -> Loaded texture SmallShipBodyDestroyed.png (25 ms)
COpenGLModel::LoadFromFile -> Loaded model ./Models/SmallShipDestroyed.ase (37 ms)
COpenGLTexture::LoadFromFile -> Loaded texture MediumBomber.png (83 ms)
COpenGLModel::LoadFromFile -> Loaded model ./Models/MediumBomber.ase (102 ms)
COpenGLModel::LoadFromFile -> Loaded model ./Models/MediumBomberPropeller.ase (4 ms)
COpenGLTexture::LoadFromFile -> Loaded texture BigBomber.png (242 ms)
COpenGLModel::LoadFromFile -> Loaded model ./Models/BigBomberPropeller.ase (253 ms)
COpenGLModel::LoadFromFile -> Loaded model ./Models/BigBomber.ase (21 ms)
Success.

Success.

COpenGLShader::Compile -> Shader link Succeeded
Success.

Success.

COpenGLShader::Compile -> Shader link Succeeded
Success.

Success.

COpenGLShader::Compile -> Shader link Succeeded
```
and a picture:
![frikingshark01](https://user-images.githubusercontent.com/3250792/55908274-4549b500-5bd9-11e9-81c2-9710c323e843.png)

**Comment by kas1e** [comment]
Daniel fix it in ogles2.library, so thanks again for your help :)
