### ISSUE TITLE
Blender port code request

### ISSUE THREAD

**Issue by lordloki** [ptitSeb/gl4es#201]
Hi, i'm one of developers of UPBGE game engine (a fork of Blender with game engine improved). This is not an issue per se but a request for help.
We saw, as one your successful examples, that you have working Blender with gl4es library. The request is if you have available the code from when you made the Blender port. That code helps us a lot to port UPBGE too.

Thanks in advance.

**Comment by ptitSeb** [comment]
Hi,

Yeah, I got blender running some time ago. It was based on blender 2.68. Anything newer will not run because the required OpenGL version was bumped up.

Sources were mostly untouched. I remeber just changing a few things to avoid multiple windows/glcontext to be created for menu handling, as the Pandora video driver had a limitation and didn't handle that well.

I have retested gl4es with blender lately, not sure it still works. I'll test again (but I first need to rebuild on my Pandora, as I updated Python in the mean time).

I haven't used a git depo on my changes, so they are not tracked. I can still probably at least isolate source file changed based on the last write date, if you are still interrested, but again, nothing major, and based on old 2.68...

**Comment by lordloki** [comment]
Thanks for the recommendations.

Currently at UPBGE we have two main branches.  One very stable one that is based on blender 2.79 (uses opengl 2.1) and another one under strong development that is based on blender 2.8x (uses opengl 3.3).

My intention is to generate a build for Android and ras pi based on blender 2.79 branch.

**Comment by ptitSeb** [comment]
Looking on my disk, I found some 2.76 source that seemed to work with gl4es. I'm rebuilding that to check if it worked. source is untouched (it's a git clone this time) exept some small changes in a CMakeList.txt

**Comment by lordloki** [comment]
Great!. Then i will start to make tests.
Thanks for the advices. I will keep you informed about our progress.
