### ISSUE TITLE
Strange stuck bug on the old Android devices

### ISSUE THREAD

**Issue by EXL** [ptitSeb/gl4es#26]
On older Android devices I get the problem with stuck when choosing some libraries through dlopen.

The bug is reproducible on *Motorola Droid 2, Android 2.3.4* and **don't affect** on my another Android devices: *Motorola Droid 4, Android 6.0.1 (CM 13)*, *Motorola Photon Q, Android 4.1.2* and huge heap of emulators.

Using debug I found a place where the app gets stuck:

https://github.com/ptitSeb/gl4es/blob/master/src/gl/loader.c#L62

I put a couple of debug-output:

![GL4ES Debug Output](http://wstaw.org/m/2017/06/09/Screenshot_20170609_082601.png)

And I got a log:

```
I/LIBGL: LIBGL: Initialising gl4es
I/LIBGL: LIBGL: v0.9.6 built on Jun  9 2017 08:03:25
I/LIBGL: Entering to this loops...
I/LIBGL: Trying to load: libbcm_host.so, flags: 0x00000000
<now app gets stuck w/ black screen>
```
I thought it was because of the RPi libraries that are not in the Android device and I commented this function calls:

![BCM Wrong Libraries](http://wstaw.org/m/2017/06/09/Screenshot_20170609_083458.png)

But it did not help. OpenGL ES and EGL libraries were not loaded too:

```
I/LIBGL: LIBGL: Initialising gl4es
I/LIBGL: LIBGL: v0.9.6 built on Jun  9 2017 08:03:25
I/LIBGL: Entering to this loops...
I/LIBGL: Trying to load: libGLESv1_CM.so, flags: 0x00000000
<now app gets stuck w/ black screen>
```

```
I/LIBGL: LIBGL: Initialising gl4es
I/LIBGL: LIBGL: v0.9.6 built on Jun  9 2017 08:03:25
I/LIBGL: Entering to this loops...
I/LIBGL: Trying to load: libEGL.so, flags: 0x00000000
<now app gets stuck w/ black screen>
```
Log from the Motorola Photon Q, Android 4.1.2 phone, where everything works:

```
I/LIBGL: LIBGL: Initialising gl4es
I/LIBGL: LIBGL: v0.9.6 built on Jun  9 2017 08:03:25
I/LIBGL: Entering to this loops...
I/LIBGL: Trying to load: libGLESv1_CM.so, flags: 0x00000000
I/LIBGL: Now Here!
I/LIBGL: LIBGL:loaded: libGLESv1_CM.so
I/LIBGL: Entering to this loops...
I/LIBGL: Trying to load: libEGL.so, flags: 0x00000000
I/LIBGL: Now Here!
I/LIBGL: LIBGL:loaded: libEGL.so
```
I tried to substitute library name with the full path (e. g. _/system/lib/egl/libEGL_POWERVR_SGX530_125.so_) to the dlopen function, but this also does not work.

Any assumptions or suggestions? Thanks!

**Comment by ptitSeb** [comment]
Yes, it's a problem with older Android version were dl_open is not recursive. here is an url with some info ( http://grokbase.com/t/gg/android-ndk/124bdvscqx/block-with-calling-dlopen-and-dlclose ), but basicaly, on version of Android oder then 4.1 I think, you cannot dlopen a lib from a dlopen.
And gl4es just does some dlopen inside a dlopen, because it use, by default, a library constructor (the funciton with `__attribute__((constructor))`
But there is a workaround.
1. In the `Android.mk`, remove the comment at line 54 ( https://github.com/ptitSeb/gl4es/blob/master/Android.mk#L54 ) to define `NO_INIT_CONSTRUCTOR`
2. In your code, as soon as you can, call `void initialize_gl4es()` to properly initialise GL4ES.

(I need to document that in main readme)

**Comment by EXL** [comment]
Many thanks for the detailed explanation. It works now!

> I need to document that in main readme

Ok! Please close this issue when you add this info to ReadMe.

**Comment by ptitSeb** [comment]
Done with 5d6a723790ef9d5842a3fe2927e9444d79344d5a
