### ISSUE TITLE
Ability to force use a supported depth format?

### ISSUE THREAD

**Issue by AbduSharif** [ptitSeb/gl4es#328]
GL4ES supports those right? Is it possible to force use one of them? (By editing gl4es code...etc?)

- GL_DEPTH_COMPONENT16
- GL_DEPTH_COMPONENT24
- GL_DEPTH_COMPONENT32

Also does gl4es support "GL_NV_depth_buffer_float" or "GL_ARB_depth_buffer_float"?

**Comment by Sisah2** [comment]
Speaking of this i still have weird issue with depth texture in openmw, it look like that texture have not enought precision, and water depth instead of smooth transition look layered, by pretty big steps. This issue seems to dont happen on all devices, but samsung phones with mali gpu are definitely affected (i had few of them). I tried different formats and types in openmw code related to setup water depth texture
https://github.com/OpenMW/openmw/blob/31e5fd91d13e4a61601eb230c823f2686f35453b/components/sceneutil/rtt.cpp#L95
GL_OES_DEPTH24 is supported on my phone.
Any idea what may be problem, or what to try?

**Comment by Sisah2** [comment]
Basicaly depth texture should look like this
![screenshot016](https://user-images.githubusercontent.com/64099446/128074006-e98693a7-ba45-4be9-a902-8a90b53dbeb1.png)
But it look like this
![Screenshot_20210803-212101_OMW_Debug](https://user-images.githubusercontent.com/64099446/128074091-e9f3d91a-bdfc-4d61-ab25-578959edde95.jpg)

**Comment by AbduSharif** [comment]
I figure this won't be answered/isn't possible so I'm closing it.

**Comment by Sisah2** [comment]
Fixed my issue changing uniform sampler2d to uniform highp sampler2d

**Comment by ptitSeb** [comment]
> GL4ES supports those right? Is it possible to force use one of them? (By editing gl4es code...etc?)
> 
> * GL_DEPTH_COMPONENT16
> * GL_DEPTH_COMPONENT24
> * GL_DEPTH_COMPONENT32

Yes they are supported

> Also does gl4es support "GL_NV_depth_buffer_float" or "GL_ARB_depth_buffer_float"?

I don't remember checking for `GL_NV_depth_buffer_float`, but `GL_ARB_depth_buffer_float` should be supported.

**Comment by ptitSeb** [comment]
> Fixed my issue changing uniform sampler2d to uniform highp sampler2d

A yes, for textures that are depth componant, forcing "highp" is probably needed!
