### ISSUE TITLE
quality difference between rendering on firefox and chrome , chrome renders very poor 

### ISSUE THREAD

**Issue by RavikumarTulugu** [ptitSeb/gl4es#365]
seeing huge quality difference between firefox and chrome using gl4es. pasting the screenshot here. I am new to this graphics, so i might be overlooking or failing to understand a trivial thing. please advise. 
I am seeing this warning from the library, both in firefox and chrome. but the firefox has no issues but chrome renders very poor.
**error:
Forcing NPOT support by disabling MIPMAP support for NPOT textures** 

_//below line from init.c triggers the error
if(strstr(Exts, "GL_ARB_texture_non_power_of_two ") || strstr(Exts, "GL_OES_texture_npot ")) hardext.npot = 3;_

my chrome gpu flags have this **GL_OES_texture_npot** in the **GL_EXTENSIONS** string. i am not sure hardext.npot is still 1 and not 3. Please advise on whether the above error has any thing to do with the below picture quality or nothing to do. 

![Screenshot_20211207_110849](https://user-images.githubusercontent.com/2748005/145684977-6c619eca-3cd7-4ff4-9c1a-cc8e33ee1b6f.png)

**Comment by ptitSeb** [comment]
The warning is you see is OK. And it's not the root cause of the issue.
The issue with the left picture is that Cubemap framebuffer doesn't seems to work properly.
Not sure what the actual problem is. But framebuffer with cubemap attached seems to gives incorrect rendering, like if the texture actually didn't attache correctly to the framebuffer.

**Comment by RavikumarTulugu** [comment]
Thanks for the pointers.i will look in to it, lets keep this open for the warning.
