### ISSUE TITLE
test-case: general, endian or amiaos4 specific #2

### ISSUE THREAD

**Issue by kas1e** [ptitSeb/gl4es#49]
Ok ! Next round :)

I have an example, which uses evaluators to generate a curved surface and automatically generated texture coordinates. That can be good test case probably and for GL4ES too.

AmigaOS4 GL4ES source: http://kas1e.mikendezign.com/aos4/gl4es/tests/testcase_2/texturesurf_gl4es.c

Now, with our old opengl1.2 it looks good, like this:
http://kas1e.mikendezign.com/aos4/gl4es/tests/testcase_2/texturesurf_mgl.jpg

Over gl4es it looks like this:
http://kas1e.mikendezign.com/aos4/gl4es/tests/testcase_2/texturesurf_gl4es.jpg

Full debug log:
http://kas1e.mikendezign.com/aos4/gl4es/tests/testcase_2/texturesurf_debug.txt

**Comment by ptitSeb** [comment]
Mmm, were are to colors!

I'll check on the Pandora if it work first.

**Comment by ptitSeb** [comment]
Looking at the code, I think this is due to using texture 0...

In `void init(void)`

after `makeImage();` add
``` 
GLuint tex;
glGenTextures(1, &tex);
glBindTexture(GL_TEXTURE_2D, tex);
```
And I think you'll see something.
I haven't tested yet on the Pandora (I let it finish a build first), but I'm pretty sure it's that.

Using texture 0 is not advised in general, but I thought I had fixed the issue. It seems there is still a bug...

**Comment by kas1e** [comment]
And you are right, all is fine after i do that change.. More of it, it all looks fine by colors, so there is even no endian problems, or os4 driver ones. At last i found something to fix in gl4es ! :) Tell me if i any of help with it , in meanwhile will cookie up something else

**Comment by ptitSeb** [comment]
Ok, commit fccb1bedf909ef06668c04eadc2f9393b7427c28 fixes the use of texture 0.

**Comment by kas1e** [comment]
Hm, seems no. Checked 2 times, also redownloaded texture.c and rebuild all again, and seems still the same.

**Comment by ptitSeb** [comment]
It is on my side. Can you upload logs of new version?

**Comment by ptitSeb** [comment]
Mmmm, looks like there is a pb on the OGLES2 side now.

in the shader there is a `uniform sampler2D _gl4es_TexSampler_0;` there is another uniform, the mat4 for the modelviewprojection
but gl4es found:
```
 uniform #0 : "_gl4es_ModelViewProjectionMatrix" (builtin)  type=GL_FLOAT_MAT4 size=1
 uniform #0 : "_gl4es_ModelViewProjectionMatrix" (builtin)  type=GL_FLOAT_MAT4 size=1
```
Yes, 2xtimes the same??? how is that possible.
But anyway, the uniform for the texture sampler is not found... so the texture number is not updated (and it's not 0, because gl4es assign another texture number internaly).

(and I'm off to bed)

**Comment by kas1e** [comment]
Hm, strange! I will try to add your replacement test code back, to see what shaders generated..maybe will bring light on what happens

**Comment by kas1e** [comment]
Do some tests with added after makeimage():

GLuint tex;
glGenTextures(1, &tex);
glBindTexture(GL_TEXTURE_2D, tex); 

Shaders generates 1:1 the same , and colors looks correct. So we can rule out shaders.

Then in log it still show me (even with good colors):

 uniform #0 : "_gl4es_ModelViewProjectionMatrix" (builtin)  type=GL_FLOAT_MAT4 size=1
 uniform #0 : "_gl4es_ModelViewProjectionMatrix" (builtin)  type=GL_FLOAT_MAT4 size=1
 attrib #0 : _gl4es_Vertex (builtin) type=GL_FLOAT_VEC4 size=1
 attrib #1 : _gl4es_Color (builtin) type=GL_FLOAT_VEC4 size=1
 attrib #2 : _gl4es_MultiTexCoord0 (builtin) type=GL_FLOAT_VEC4 size=1

How your part of log looks like there ?

**Comment by kas1e** [comment]
In the version without adding of those glgentextures/glbindtexture, output about uniforms the same too..

**Comment by ptitSeb** [comment]
Well, we have 2 issue here, but I'm afraid they both are in OGLES2 driver.

First issue is that "hidden" uniform. I'm not sure if it's because it's a Sampler or because the uniform is in the fragment shader, but there is an issue here. Now, for now it's not important as long as you are not doing multi-texture, because, by default, the Sampler will address Texture Unit 0, so single-texture shader will work. Still, it's a bug and it should be fixed.

Second issue is accessing Texture 0. As you have notice, in gl4es the texture number 0 (do not mix with Texture Unit 0) is a special case. Most of the time, you use Texture 0 to "unbind" texture. But it's wrong. Texture 0 can be use like any other texture you get with `glGenTextures(...)`. In fact, OpenGL let you even use any texture number yo like, you are not require to create a texture with `glGenTextures(...)` at all. `glGenTextures` is just there to make sure each texture number you get is unique. Anyway, with gl4es, all texture are created with `glGenTextures(...)`, even if don't use it in your program. With the exeption of texture 0... SO I think OGLES2 driver has a bug and doesn't allow uploading texture data to Texture 0.

**Comment by kas1e** [comment]
Thanks for detailed answer, will write BZ again to ogles driver.

Btw , did i understand right, you didn't have 2 times :

uniform #0 : "_gl4es_ModelViewProjectionMatrix" (builtin) type=GL_FLOAT_MAT4 size=1
uniform #0 : "_gl4es_ModelViewProjectionMatrix" (builtin) type=GL_FLOAT_MAT4 size=1

But only 1 time ?

**Comment by ptitSeb** [comment]
I would expect:
```
uniform #0 : "_gl4es_ModelViewProjectionMatrix" (builtin) type=GL_FLOAT_MAT4 size=1
uniform #1 : "_gl4es_TexSampler_0" (builtin) type=GL_SAMPLER_2D size=1
```

**Comment by kas1e** [comment]
Thanks ! I send all the info to developer, fingers crossed on fast fix :)

**Comment by kas1e** [comment]
@ptitSeb
Daniel (author of our ogles2), almost fixed both issues, but just want us to note, that in one place gl4es seems lack an error-check via glGetError, and that's why that dupe appears.  In case of an error glGetActiveUniform doesn't modify the name string etc., so gl4es prints the one from the previous successful call => we see dupe.

He almost done with fixes, but as it all going nicely with gl4es, maybe you can/want change logging at that point (program.c  around line 556) to avoid confusion.  As without, it actually made him look at the wrong area first (he thought the cached info of the sampler-variable would accidentially be overwritten 
by the uniform matrix).

More logging the better as usual :)

**Comment by ptitSeb** [comment]
Sure, I'll add some debug logging in the Uniform and Attribute enumeration in DEBUG mode.

**Comment by kas1e** [comment]
And i recieve fixed drivers, so in logs and visually all looks fine => we can close ticket until next ruound :)

Thanks !
